[project]
name = "cloud-pipelines-backend"
version = "0.1.0"
description = "Backend for Cloud Pipelines"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.18.5",
    "bugsnag>=4.9.1,<5",
    "cloud-pipelines>=0.26.7.29",
    "fastapi[standard]>=0.139.2",
    "kubernetes>=36.0.3,<37",
    "opentelemetry-api>=1.44.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.41.1",
    "opentelemetry-exporter-otlp-proto-http>=1.39.1",
    "opentelemetry-instrumentation-fastapi>=0.60b1",
    "opentelemetry-sdk>=1.39.1",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "kubernetes-stubs-elephant-fork>=36.0.3.post1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
huggingface = [
    "huggingface-hub[oauth]>=0.35.3",
]
skypilot = [
    "skypilot>=0.13.0",
]

[tool.uv]
exclude-newer = "7 days"
index-url = "https://pypi.org/simple"
extra-index-url = []

[tool.uv.exclude-newer-package]
cloud-pipelines = false

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--import-mode=importlib"
[tool.setuptools.packages.find]
include = ["cloud_pipelines_backend*"]
namespaces = true
