name: Black Code Formatter

on: [push, pull_request]

permissions:
  contents: read

jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
